[IOPID-729] : handler exchange
pagopa/io-web-profile-backend pull request #16
Opened 2023-09-11 08:47 UTC by pelliccm

#### List of Changes

Handler for Exchange API

#### Motivation and Context

Permit users to log in using the token from magic link to generate a new one

#### How Has This Been Tested?

Unit tests, Postman

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-09-25 09:47 UTC, BurnedMarshal requested changes

2023-09-25 09:47 UTC, BurnedMarshal commented on utils/exchange-jwt.ts
>      token_type: NonEmptyString
What are all the possible and valid values for `token_type`?

2023-09-25 09:47 UTC, BurnedMarshal commented on utils/jwe.ts
> +const getKeyLikeFromString = (
```suggestion
/**
 * Take in input a PEM-encoded PKCS#8 key string and
 * returns an Either with an error or a KeyLike object
 */
const errorOrKeyLikeFromString = (
```

2023-09-25 09:47 UTC, BurnedMarshal commented on utils/jwe.ts
> +  );
If we use `jwtDecrypt` method the most of the validation is done by the library itself.

```suggestion
export const validateJweWithKey = (
  token: NonEmptyString,
  jwePrivateKey: NonEmptyString,
  issuer: NonEmptyString
): TE.TaskEither<Error, BaseJwePayload> =>
  pipe(
    getKeyLikeFromString(jwePrivateKey),
    TE.chain(pkcs8 =>
      TE.tryCatch(() => jose.jwtDecrypt(token, pkcs8, { issuer }), E.toError)
    ),
    TE.mapLeft(e => new Error(`Error decrypting Magic Link JWE: ${e}`)),
    TE.chain(
      flow(
        BaseJwePayload.decode,
        E.mapLeft(
          err =>
            new Error(`Invalid JWE payload: ${readableReportSimplified(err)}`)
        ),
        TE.fromEither
      )
    )
  );
```

2023-09-25 09:47 UTC, BurnedMarshal commented on utils/middlewares/magic-link-jwe-validation-middleware.ts
> +  config: IConfig
Pass a subset of the whole configuration.

2023-09-25 09:47 UTC, BurnedMarshal commented on utils/middlewares/magic-link-jwe-validation-middleware.ts
> +export const magicLinkJweValidation = (config: IConfig) => (
ditto

2023-09-25 11:22 UTC, arcogabbo reviewed
nice work. I have some suggestions

2023-09-25 11:22 UTC, arcogabbo commented on utils/jwe.ts
do we need line 68? I think [this](https://github.com/pagopa/io-web-profile-backend/pull/18#discussion_r1330177902) comment was not addressed
```ts
 TE.mapLeft(e => E.toError(`Error: ${e}`)),
```

2023-09-25 11:22 UTC, arcogabbo commented on Exchange/handler.ts
> +const EXCHANGE_TOKEN_TYPE = "exchange" as NonEmptyString;
```suggestion
```
you can remove this and use the enum `TokenTypes` you defined. I also would suggest to change the enum to a `t.literal`. 
Enums are used to identify a set of constants but in this specific use case there is only ONE constant described there. by the way I don't have a strong opinion on this so maybe @gquadrati and @BurnedMarshal have more insights

2023-09-25 11:22 UTC, arcogabbo commented on Exchange/handler.ts
> +  )();
```suggestion
export const exchangeHandler = (config: IConfig): ExchangeHandlerT => (
  user_data: BaseJwePayload
): ReturnType<ExchangeHandlerT> =>
  pipe(
    getGenerateExchangeJWT(config)({
      family_name: user_data.family_name,
      fiscal_number: user_data.fiscal_number,
      name: user_data.name,
      token_type: TokenTypes.EXCHANGE
    }),
    TE.mapLeft(e =>
      ResponseErrorInternal(`Cannot generate Exchange JWT|ERROR=${e.message}`)
    ),
    defaultLog.taskEither.errorLeft(
      r => r.detail ?? "Cannot generate Exchange JWT"
    ),
    TE.map(ResponseSuccessJson),
    TE.toUnion
  )();
```
I would simplify this handler as I suggested above because there are some things that aren't needed. let me know what you think

2023-09-26 13:01 UTC, gquadrati requested changes

2023-09-26 13:01 UTC, gquadrati commented on utils/__tests__/exchange-jwt.test.ts
> +  });
Decode it and verify that the content matches the payload, like [here](https://github.com/pagopa/hub-spid-login-ms/blob/3fd714443879339e7efbb6a661e206081a41952f/src/utils/__tests__/jwt.test.ts#L57C20-L57C20)

2023-09-26 13:01 UTC, gquadrati commented on Exchange/handler.ts
> +const EXCHANGE_TOKEN_TYPE = "exchange" as NonEmptyString;
I totally agree. I believe we can safely use the enum in this PR and subsequently initiate a new PR for the refactoring using `t.literal`.

2023-09-26 13:01 UTC, gquadrati commented on utils/middlewares/magic-link-jwe-validation-middleware.ts
> +  );
We should add some tests, one for each of the following input:
- a valid token
- an invalid token
- an expired token

2023-09-26 13:29 UTC, gquadrati commented on Exchange/handler.ts
> +  )();
Agree with @arcogabbo

2023-09-27 06:31 UTC, gquadrati requested changes
Some tests are failing, and there are still unresolved comments.

2023-09-27 10:21 UTC, gquadrati commented
/azp run

2023-09-27 10:25 UTC, gquadrati approved these changes

2023-09-27 10:26 UTC, merged