[IOPID-731] : bff unit test
pagopa/io-web-profile-backend pull request #17
Opened 2023-09-13 09:05 UTC by pelliccm

#### List of Changes

Unit tests for exchange-jwt-validation and user-eligibility middlewares. 
Files required to make them work (also included in [IOPID-729 PR](https://github.com/pagopa/io-web-profile-backend/pull/16))

#### Motivation and Context

Testing middlewares, functions and higher coverage

#### How Has This Been Tested?

Unit tests

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2023-09-19 18:51 UTC, gquadrati requested changes
LGTM, just a few small changes

2023-09-19 18:51 UTC, gquadrati commented on README.md
> +| FUNCTIONS_APP_SUBSCRIPTION_KEY  | Io Functions App Api Key                            | string|
This should be a function key `FUNCTIONS_APP_API_KEY`. Change it also in `config.ts`

2023-09-19 18:51 UTC, gquadrati commented on Info/handler.ts
> +) => healthcheck.HealthCheck<"AzureStorage" | "Config", true>;
Unit tests are failing because of this change.

2023-09-19 18:51 UTC, gquadrati commented on utils/featureFlags/__test__/featureFlags.test.ts
> +  });
We can copy tests from https://github.com/pagopa/io-functions-services/blob/master/utils/__tests__/featureFlag.test.ts

2023-09-19 18:51 UTC, gquadrati commented on SessionState/__test__/handler.test.ts
> +      THEN the response should be 500`, async () => {
As a suggestion, in future consider the option of making similar tests parametric using `it.each`.

2023-09-19 18:51 UTC, gquadrati commented on SessionState/__test__/handler.test.ts
> +      kind: "IResponseErrorInternal"
We could check `detail` too.

2023-09-20 07:34 UTC, pelliccm commented on README.md
> +| FUNCTIONS_APP_SUBSCRIPTION_KEY  | Io Functions App Api Key                            | string|
I corrected this in [another PR](https://github.com/pagopa/io-web-profile-backend/pull/16/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

2023-09-20 12:35 UTC, gquadrati approved these changes
LGTM, thanks!

2023-09-20 12:39 UTC, merged