[IOPID-1381] - LogOut AuditLog
pagopa/io-web-profile-backend pull request #34
Opened 2024-01-29 13:24 UTC by ClaudioNTT

#### List of Changes
Adding adutilog to logout call 

#### Motivation and Context
It has been introduced as requested by task [IOPID-1381](https://pagopa.atlassian.net/browse/IOPID-1381)

#### How Has This Been Tested?
Installed Azurite in the development environment to test the functionality as per Microsoft documentation
Adjusted unit tests

#### Types of changes

- [ ] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation/tests accordingly.

[IOPID-1381]: https://pagopa.atlassian.net/browse/IOPID-1381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-01-31 15:14 UTC, arcogabbo reviewed
nice work, I leaved some questions in comments

2024-01-31 15:14 UTC, arcogabbo commented on utils/jwt.ts
> +  jti: NonEmptyString,
`JwtPayloadExtended` type in `Exchange/handler.ts` already has those fields in it. you need to remove the redundant fields in `Exchange/handler.ts`

2024-01-31 15:14 UTC, arcogabbo commented on utils/exchange-jwt.ts
> +  token_type: enumType(TokenTypes, "tokenType")
can you explain why this change is needed?

2024-01-31 15:14 UTC, arcogabbo commented on utils/audit-log.ts
> +  Type: t.keyof({ [TokenTypes.EXCHANGE]: null, [TokenTypes.LOGOUT]: null })
have you tried `  Type: enumType(TokenTypes, "tokenType")
` for this field?

2024-01-31 15:14 UTC, arcogabbo commented on Logout/__test__/handler.test.ts
> +        .mockReturnValueOnce(TE.left(("" as unknown) as RestError));
I would suggest this edit if you don't mind
```suggestion
      const anError = "anError";
      const mockAuditLog = jest
        .spyOn(auditLog, "storeAuditLog")
        .mockReturnValueOnce(TE.left(new RestError(anError)));
```

2024-01-31 15:14 UTC, arcogabbo commented on Logout/__test__/handler.test.ts
> +      });
```suggestion
      expect(res).toMatchObject({
        kind: "IResponseErrorInternal",
        detail: expect.stringContaining(anError)
      });
```

2024-02-01 08:09 UTC, ClaudioNTT commented on utils/audit-log.ts
> +  Type: t.keyof({ [TokenTypes.EXCHANGE]: null, [TokenTypes.LOGOUT]: null })
much better, thanks!

2024-02-01 08:18 UTC, ClaudioNTT commented on utils/jwt.ts
> +  jti: NonEmptyString,
absolutely

2024-02-01 09:02 UTC, ClaudioNTT commented on utils/exchange-jwt.ts
> +  token_type: enumType(TokenTypes, "tokenType")
Because BaseJwtPayload has the JTI and IAT properties, if I use the same type, I encounter this error:

{"detail":"Cannot generate Exchange JWT|ERROR=Bad \"options.jwtid\" option. The payload already has an \"jti\" property.","status":500,"title":"Internal server error"}

2024-02-01 13:56 UTC, gquadrati requested changes

2024-02-01 13:56 UTC, gquadrati commented on utils/enums/TokenTypes.ts
>  }
Since `TokenTypes` is used to validate the JWT token (see [here](https://github.com/pagopa/io-web-profile-backend/blob/2386909840a8311cb87294e75b10ad102bb2e539/utils/middlewares/exchange-jwt-validation-middleware.ts#L41)) I think it's safer to create a completely new type, like `OperationType`.

2024-02-01 15:49 UTC, ClaudioNTT commented on utils/enums/TokenTypes.ts
>  }
Ok, I've created the OperationType as suggested

2024-02-02 17:22 UTC, gquadrati requested changes

2024-02-02 17:22 UTC, gquadrati commented on utils/audit-log.ts
> +});
According to the RFC, the content should include both the IP and the complete content of the JWT (with the fiscal code in plaintext)

2024-02-05 08:29 UTC, gquadrati requested changes

2024-02-05 08:29 UTC, gquadrati commented on utils/audit-log.ts
> +
Either maintain old `AuditLogTags` or create a codec for each type (Exchange and DispositiveAction tags)

2024-02-05 08:29 UTC, gquadrati commented on utils/audit-log.ts
>  ): TE.TaskEither<RestError, BlockBlobUploadResponse> =>
For matching right content and tag types, we can use [function overloading](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads)

2024-02-05 16:09 UTC, gquadrati approved these changes
LGTM, thanks!

2024-02-05 16:10 UTC, merged